name: resume_maker
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  hive: 
  path_provider: 
  image_picker: ^1.1.2
  getwidget: ^4.0.0
  http: ^1.2.1
  pdf:
  printing:
  rxdart: ^0.28.0
  shared_preferences:
  scoped_model: ^2.0.0
  cloud_firestore: ^4.1.0
  google_mobile_ads: ^1.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_colorpicker: 
  flutter_speed_dial:
  flutter_screenutil: 
  circular_menu: ^2.0.1
  gusto_neumorphic: ^3.3.0
  lottie: ^2.3.1
  double_tap_to_exit: ^1.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/social/